on:
  workflow_dispatch:

jobs:
  generate-inventory:
    runs-on: [ ansible-master ]

    steps:
     

      - name: Create inventory directory
        run: |
          sudo -u lourde mkdir -p /home/lourde/ansible/
          sudo chown -R lourde:lourde /home/lourde/ansible

      - name: Generate inventory.yaml
        run: |
          sudo -u lourde bash -c 'cat > /home/lourde/ansible/inventory.yaml' << 'EOF'
          ---
          all:
            children:
              webservers:
                hosts:
                  web01:
                    ansible_host: 10.158.0.3 # node1
                    ansible_user: lourde
                    

              databases:
                hosts:
                  db01:
                    ansible_host: 10.190.0.8 # node2
                    ansible_user: lourde
                    db_version: 14
                   

              
          EOF
